### ISSUE TITLE
Getting: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by slashTPA** [benklop/zenphoto-precache#1]
Hi, 
I'm getting following error and would need some hint to fix:

------------------------------------------------------------
# python precache.py
  File "precache.py", line 87
    if args.verbose: print('Scanning (',end="")
                                           ^
SyntaxError: invalid syntax

------------------------------------------------------------

by the way I'm on: 

# python -V
Python 2.7.5

Thx. & Cheers,
Tom

**Comment by benklop** [comment]
@paetzoldthomas sorry for not noticing this sooner! I've pushed some changes that I *think* should fix this issue - I created this script using python 3 and never tested it with 2.7.

**Comment by benklop** [comment]
I've tested using python 2.7 now with the latest commit, and it works properly.

**Comment by slashTPA** [comment]
Thanks. I will try to test it later, right now I end up with "ImportError: No module named phpserialize" so looks like something with my installation is missing...

**Comment by benklop** [comment]
@paetzoldthomas yeah, that module is needed to read the list of sizes to cache. i didn't include and installation instructions i guess... you should be able to `pip install` each one of the missing modules, though.

**Comment by slashTPA** [comment]
Hi, 

I tried to install all the modules, but:

No matching distribution found for imghdr
No matching distribution found for yaml

resulting in :

ImportError: No module named yaml    :-(

----------- here what I get when : pip install yaml
Collecting yaml
Could not find a version that satisfies the requirement yaml (from versions: )
No matching distribution found for yaml

**Comment by benklop** [comment]
@paetzoldthomas imghdr is part of python, so you shouldn't need to install it separately. The yaml module is called 'pyyaml'. I'll add some instructions to the readme.
